In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
arr
type(arr)

numpy.ndarray

In [5]:
import datetime

A = datetime.datetime.now()
print(A)

x = abs(-6.87878)
x

2022-12-31 13:41:04.647105


6.87878

In [6]:
import math

x = math.sqrt(64)

print(x)

8.0


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr[1]

2

In [11]:
arr[1] + arr[2]

5

In [53]:
x = np.array([[2,3,8,7],[4,6,8,0]])
x
x[1,-2]
x.shape

(2, 4)

In [47]:
A = np.array([1,2,3,4,56,7,3,6,9])
A[1:5]
A[:6]
A[-3:-1]

array([3, 6])

In [54]:
import numpy as np
A = np.array([12,34,5,66,8,89,7,9,0])
print(A[-2:-3])
A.shape

[]


(9,)

In [51]:
D = np.array(['apple', 'banana', 'cherry'])
print(D.dtype)

<U6


In [115]:
F = np.array([2,3,4,5,6,7,8,9,90,0,7,65,4,3,2,1])
A = F.reshape(2,8)
new = F.reshape(4,1,4)
new
A

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [90,  0,  7, 65,  4,  3,  2,  1]])

In [99]:
arr1 = np.array([[1,2,3], [2,34,5]])
arr2 = np.array([[10,21,33], [32,4,4]])
arr = np.concatenate((arr1,arr2), axis=1)
arr

array([[ 1,  2,  3, 10, 21, 33],
       [ 2, 34,  5, 32,  4,  4]])

In [132]:
import numpy as np

arr = np.array([1,2,3,7,8,9,6,5,4,3,3,1])
arr1 = np.array_split(arr, 7)
arr1

[array([1, 2]),
 array([3, 7]),
 array([8, 9]),
 array([6, 5]),
 array([4, 3]),
 array([3]),
 array([1])]